### ISSUE TITLE
Is it possible to execute "bundle cache" command in git cloned directory?

### ISSUE THREAD

**Issue by hiroyuki-sato** [ydkn/capistrano-git-copy#11]
Hello

I would like to execute ``bundle package `` in git cloned root.
Is it possible to execute ``bundle package `` command in git cloned directory?

Thank you for your advice.

--
Hiroyuki Sato.

**Comment by ydkn** [comment]
Hi,

I did something like that a year ago: https://github.com/SICSoftwareGmbH/capistrano-bundle-copy

In my opinion this shouldn't be directly integrated into `capistrano-git-copy` - thinking about this I found two things I'd like to do:

* I will add the possibility to hook into it's functionallity before packaging for upload so you can add stuff to the archive (sadly this means archiving has to be done twice because `git-archive-all` can only create archives). This way it's possible to add anything before upload not limited to bundled gems.

* The main problem with this is that adding all gems to the archive every time means that it will drastically grow in size - so creating an additional plugin which uses the working copy used by `capistrano-git-copy` and only uploads changed gems seems necessary to avoid that deploying gets annoyingly slow.

**Comment by ydkn** [comment]
I created an early version for the second point: https://github.com/ydkn/capistrano-git-copy-bundle

**Comment by hiroyuki-sato** [comment]
Hi sorry reply late. I was on holiday for last week. 

It seems capistrano-git-copy-bundle is cool! 
I'll try it. Thanks.

**Comment by hiroyuki-sato** [comment]
Lately, I'm using capistrano-git-copy-bundle for my app deployment.
It's work well thanks!!.

Feedback.
I would like to clean temporary directory. 
ie) cap production git_copy:bundle:clean

Because I created my custom gem with same version number. (It's my mistake)
(OSX /var/folders/rc/t8w2gc117sxghrk6pdkfq3qc0000gp/T..)

Thanks.

**Comment by ydkn** [comment]
There's now a _clear_ task, which deletes all gems from the local and remote cache directories.
```
cap production git_copy:bundle:clear
```

To be compliant with _capistrano-git-copy_ you should now require 'capistrano/git_copy/bundle' in your Capfile.

I'm closing this issue - features/issues can be discussed here: https://github.com/ydkn/capistrano-git-copy-bundle/issues

I'd like to release this gem now on rubygems.org - so if the changes didn't break anything in your setup it's good to go.
